### ISSUE TITLE
Support use with 'auto' task

### ISSUE THREAD

**Issue by adamrenklint** [immoh/lein-nsorg#1]
This plugin is great, and I'd love to be able to add it to my always-running code formatting task, running with https://github.com/weavejester/lein-auto and https://github.com/kouphax/lein-cooper. But at the end of the task, you call either `lein/summary` or `lein/abort` and then the process exits.

**Comment by immoh** [comment]
Great to hear that you find the plugin useful!

Did you verify that it doesn't work with `lein auto`?

I haven't tried it myself but `lein auto` is setting `leiningen.core.main/*exit-process?*` to `false` (https://github.com/weavejester/lein-auto/blob/master/src/leiningen/auto.clj#L36) and `summary` and `abort`should honor this according to the documentation.

**Comment by adamrenklint** [comment]
Sorry, my bad. Was using `auto` and `cooper` wrong. Works great 👍🏻
