### ISSUE TITLE
Throwing error when unmatched delimiter

### ISSUE THREAD

**Issue by adamrenklint** [immoh/lein-nsorg#3]
I have `lein-nsorg` running all the time, along with `cljfmt`.
If I accidentally save source code with invalid format, i.e. unmatched delimiter, the nsorg task will crash and stop my lein JVM. cljfmt will just show a message: `Failed to format file: src/foo/bar.cljs`.

Maybe it would be good to have the same behavior as cljfmt in nsorg, to make it suitable to run in a long-running process with `lein-auto` and `lein-cooper`?

**Comment by immoh** [comment]
Thanks for the feedback! I agree that this would be great improvement.

**Comment by immoh** [comment]
Released 0.1.4 with fix for this
