### ISSUE TITLE
Applicable to 'project.clj' dependencies?

### ISSUE THREAD

**Issue by wontheone1** [immoh/lein-nsorg#5]
Would it makes sense this plugin also organize project.clj with it's dependencies and plugins?

Best regards,

**Comment by immoh** [comment]
Hey Won,

Sorry for taking long time to respond. I gave this a little thought and I think this plugin (and library) should focus on ns forms and not be extended to Leiningen project.clj dependencies. I am sure there are many other things that could be also organized so the line has to be drawn somewhere.

**Comment by wontheone1** [comment]
No worries,

Totally understandable and agreeable decision,
just needed to check the your intention for this project.

👍
